---
- name: Ensure smi_smiservices_install_root exists
  become: true
  ansible.builtin.file:
    name: "{{ smi_smiservices_install_root }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Deploy SmiServices versions
  become: true
  environment: "{{ proxy_env | default({}) }}"
  ansible.builtin.script:
    cmd: |
      deploy_smiservices.py \
        {{ smi_smiservices_base_url }} \
        {{ smi_smiservices_install_root }} \
        '{{ smi_smiservices_versions | to_json }}'
  register: deploy_result
  changed_when: deploy_result.rc != 0
