---
hicservices_rdmp_smi_root_dir: "{{ smi_root_dir | default(lookup('env', 'HOME') ~ '/smi') }}"
hicservices_rdmp_base_dir: "{{ hicservices_rdmp_smi_root_dir }}/software/HicServices/RDMP"

hicservices_rdmp_base_url: "https://github.com/HicServices/RDMP/releases/download"
hicservices_rdmp_versions:
  "8.1.0":
    packages:
      - name: rdmp-<VERSION>-cli-linux-x64.tar.xz
        checksum: "sha256:D3272CD6684B09AE295723138F124F570C28DC05D055CCC480A20B4F2992E638"
        file_blocklist:
          - Databases.yaml
          - NLog.config
