---
ci:
  # NOTE(rkm 2023-11-21) ansible-lint exceeds pre-commit.ci free tier size, so we run it via GitHub Actions
  skip: [ansible-lint]

default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      # General
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      # Python
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: debug-statements
  # General
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/rkm/pre-commit-nocommit
    rev: "v1.0.0"
    hooks:
      - id: nocommit
        exclude: .pre-commit-config.yaml
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.3.0"
    hooks:
      - id: codespell
        args:
          [
            --ignore-words,
            .meta/codespell-ignores,
            --exclude-file,
            .meta/codespell-excludes,
            --ignore-regex,
            '\Whttps?://\S*',
          ]
  # Markdown
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.19
    hooks:
    - id: mdformat
      additional_dependencies:
        - mdformat-gfm==0.3.6
  # Python
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: python-no-log-warn
  - repo: https://github.com/asottile/reorder-python-imports
    rev: "v3.14.0"
    hooks:
      - id: reorder-python-imports
        args: [--py310-plus]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: "v3.1.0"
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.19.0"
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/asottile/yesqa
    rev: "v1.5.0"
    hooks:
      - id: yesqa
        additional_dependencies: [pep8-naming==0.14.1]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.13.0"
    hooks:
      - id: mypy
        args: [--config-file, .meta/mypy.ini, --scripts-are-modules]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: "24.10.0"
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: "7.1.1"
    hooks:
      - id: flake8
        additional_dependencies:
        - flake8-bugbear==24.4.26
        - flake8-assert-msg==1.1.1
        - pep8-naming==0.14.1
        args: [--config, .meta/flake8.conf]
  # Yaml
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.35.1"
    hooks:
      - id: yamllint
        args: [-c, .meta/yamllint.yaml]
  # Ansible
  - repo: https://github.com/ansible/ansible-lint.git
    rev: "v24.10.0"
    hooks:
      - id: ansible-lint
        args:
          [--config, .meta/ansible-lint.yml]
        additional_dependencies:
          - ansible==10.1.0
          - jmespath==1.0.1
  # Shell
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "v0.10.0.1"
    hooks:
      - id: shellcheck
        args: [--enable=all]
  # Local
  - repo: local
    hooks:
      - id: ansible-managed-in-templates
        name: ansible-managed-in-templates
        entry: .meta/ansible-managed-in-templates
        language: system
        files: "^roles/.*/templates/.*$"
        types: [text]
