---
namespace: smi
name: playbook
version: 0.1.0
readme: README.md
authors:
  - Ruairidh MacLeod (ruairidh@rkm.dev)
description: SMI playbook collection
license:
  - MIT
repository: https://github.com/SMI/playbook
issues: https://github.com/SMI/playbook/issues
