---
namespace: smi
name: ansible
version: 0.1.0
readme: README.md
authors:
  - Ruairidh MacLeod (ruairidh@rkm.dev)
description: SMI Ansible collection
license:
  - MIT
repository: https://github.com/SMI/ansible
issues: https://github.com/SMI/ansible/issues
tags: [application]
