---
- name: Run preflight role on all hosts
  hosts: all
  gather_facts: true
  roles:
    - 00_preflight
  tags: [always]
- name: Start Docker services
  hosts: all
  roles:
    - 02_docker_services
  tags: [never, docker]
- name: Run service-software role on specified hosts
  hosts: service_software,smi_aio_build,localhost
  roles:
    - 10_service_software
  tags: [software]
