---
- name: Run all roles
  hosts: "{{ target | default('software_host') }}"
  gather_facts: true
  roles:
    - role: smi_root
      tags: [always]
    - role: bin
      tags: [bin]
    - role: envs
      tags: [envs]
    - role: smi_smiservices
      tags: [smiservices]
    - role: smi_isidentifiable
      tags: [isidentifiable]
    - role: smi_structuredreports
      tags: [structuredreports]
    - role: smi_dicompixelanon
      tags: [dicompixelanon]
    - role: hicservices_rdmp
      tags: [rdmp_cli]
    - role: smi_cogstack_semehr
      tags: [cogstack_semehr]
    - role: smi_ctp_anon_cli
      tags: [ctp_anon_cli]
