---
- name: Run all roles
  hosts: "{{ target | default('software_host') }}"
  gather_facts: true
  roles:
    - role: smi_root
      tags: [always]
    - role: bin
      tags: [bin]
    - role: configs
      tags: [configs]
    - role: smi_smiservices
      tags: [smiservices]
    - role: smi_isidentifiable
      tags: [isidentifiable]
    - role: hicservices_rdmp
      tags: [rdmp_cli]
