---
- name: Run preflight checks
  hosts: all
  gather_facts: true
  roles:
    - preflight
  tags: [always]
- name: Run service-software role on specified hosts
  hosts: software_hosts
  roles:
    - 10_service_software
  tags: [software]
