---
# {{ ansible_managed }}

RabbitOptions:
  RabbitMqHostName: "localhost"
  RabbitMqHostPort: 5672
  RabbitMqVirtualHost: "smi_{{ env['name'] }}_file_extract"
  RabbitMqUserName: "guest"
  RabbitMqPassword: "guest"
  RabbitMqControlExchangeName: "ControlExchange"
  FatalLoggingExchange: "FatalLoggingExchange"

LoggingOptions:
  LogConfigFile: "{{ template_destpath | dirname }}/NLog.config.xml"
  LogsRoot: "/tmp/smi/logs/{{ env['name'] }}"
  TraceLogging: true

FileSystemOptions:
  FileSystemRoot: "/tmp/smi/PACS"
  ExtractRoot: "/tmp/smi/extract"
  DicomSearchPattern: "*.dcm"

RDMPOptions:
  CatalogueConnectionString:
  YamlDir:
  DataExportConnectionString:

MongoDatabases:
  ExtractionStoreOptions:
    HostName: "localhost"
    Port: 27017
    UserName:
    Password:
    DatabaseName: "extraction"

ExtractImagesOptions:
  MaxIdentifiersPerMessage: 1000
  ExtractionRequestProducerOptions:
    ExchangeName: "RequestExchange"
    MaxConfirmAttempts: 1
  ExtractionRequestInfoProducerOptions:
    ExchangeName: "RequestInfoExchange"
    MaxConfirmAttempts: 1

CTPAnonymiserOptions:
    VerifyRoutingKey: verify
    NoVerifyRoutingKey: noverify
    SRAnonTool: "{{ configs_smi_root_dir }}/software/SMI/StructuredReports/SMI-StructuredReports-{{ env['structuredreports_version'] }}/src/applications/SRAnonTool/CTP_SRAnonTool.sh"
    AnonFileConsumerOptions:
        QueueName: 'ExtractFileAnonQueue'
        QoSPrefetchCount: 1
        AutoAck: false
    ExtractFileStatusProducerOptions:
        ExchangeName: 'ExtractedFileStatusExchange'
        MaxConfirmAttempts: 5
