---
- name: Ensure smi_root_smi_root_dir exists
  become: true
  ansible.builtin.file:
    name: "{{ smi_root_smi_root_dir }}"
    state: directory
    owner: "{{ ansible_become_user | default('root') }}"
    group: "{{ smi_root_smi_group }}"
    mode: u=rwx,g=rx,o=

- name: Template README.md
  become: true
  ansible.builtin.template:
    src: root_readme.md
    dest: "{{ smi_root_smi_root_dir }}/README.md"
    mode: u=rw,g=r,o=r
