---
- name: Ensure smi_root_smi_root_dir exists
  ansible.builtin.file:
    name: "{{ smi_root_smi_root_dir }}"
    state: directory
    group: "{{ smi_root_smi_group }}"
    mode: u=rwx,g=rx,o=rx

- name: Template README.md
  ansible.builtin.template:
    src: root_readme.md
    dest: "{{ smi_root_smi_root_dir }}/README.md"
    mode: u=rw,g=r,o=r
