---
- name: Start or stop services
  community.docker.docker_compose:
    project_name: smi
    state: "{{ smi_docker_services_state }}"
    definition:
      version: "3.7"
      services:
        rabbitmq:
          container_name: rabbitmq
          image: rabbitmq:management
          user: rabbitmq
          ports:
            - 5672:5672
            - 15672:15672
        mongodb:
          container_name: mongodb
          image: mongo:latest
          command: mongod --replSet rs0
          ports:
            - 27017:27017
        mariadb:
          container_name: mariadb
          image: mariadb:latest
          environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-YourStrongPassw0rd}
          ports:
            - 3306:3306
        redis:
          container_name: redis
          image: redis:latest
          ports:
            - 6379:6379
  notify: "docker_services : Enable MongoDB replication"
