---
- name: Create software dir
  become: true
  ansible.builtin.file:
    path: "{{ hicservices_rdmp_install_root }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Deploy rdmp-cli versions
  become: true
  ansible.builtin.script:
    cmd: |
      deploy_rdmp_cli.py \
        {{ hicservices_rdmp_base_url }} \
        {{ hicservices_rdmp_install_root }} \
        '{{ hicservices_rdmp_versions | to_json }}'
  register: deploy_result
  changed_when: deploy_result.rc != 0
