---
- name: Ensure hicservices_rdmp_base_dir exists
  ansible.builtin.file:
    path: "{{ hicservices_rdmp_base_dir }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Deploy rdmp-cli versions
  environment: "{{ proxy_env | default({}) }}"
  ansible.builtin.script:
    cmd: |
      deploy_rdmp_cli.py \
        {{ hicservices_rdmp_base_url }} \
        {{ hicservices_rdmp_base_dir }} \
        '{{ hicservices_rdmp_versions | to_json }}'
  register: deploy_result
  changed_when: deploy_result.rc != 0
