---
smi_smiservices_base_url: "https://github.com/SMI/SmiServices/releases/download"
smi_smiservices_install_root: "{{ smi_root_software_dir }}/SMI/SmiServices"
smi_smiservices_versions:
  "5.6.1":
    packages:
      - name: smi-services-v<VERSION>-linux-x64.tgz
        checksum: "md5:0b1c56ed8c8e449354eadea46971d55e"
        file_blocklist:
          - default.yaml
          - DynamicRules.txt
          - Rules.template.yaml
          - Smi.NLog.config
      - name: ctpanonymiser-v<VERSION>.zip
        checksum: "md5:e4d3eb66a0e003195a4deb25f4fa60fe"
      - name: SmiServices-<VERSION>-py3-none-any.whl
        checksum: "md5:0af6e06d824c5909b5c6ea786228a853"
