---
- name: Ensure config dir exists
  become: true
  ansible.builtin.file:
    path: "{{ smi_service_software_install_dir }}/configs/{{ config_name }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Ensure config logs dir exists
  become: true
  ansible.builtin.file:
    path: "{{ smi_service_software_logs_dir }}/{{ config_name }}"
    owner: root
    group: "{{ preflight_group_name }}"
    state: directory
    mode: u=rwx,g=rwxs,o=

- name: Read "config_smiservices_version" from env.bash
  ansible.builtin.set_fact:
    config_smiservices_version: "{{
      lookup('ansible.builtin.file', env_path) |
      regex_search('SMI_SMISERVICES_VERSION=\"(.*)\"', '\\1') |
      first }}"
  vars:
    env_path: "{{ smi_service_software_local_configs_template_dir }}/{{ config_name }}/env.bash"

- name: Template config files
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ smi_service_software_install_dir }}/configs/{{ config_name }}/{{ item | basename }}"
    mode: u=rw,g=r,o=r
  with_ansible.builtin.fileglob: "{{ smi_service_software_local_configs_template_dir }}/{{ config_name }}/*"
  register: config_files
  notify: "service_software : Upload changed RabbitMQ configs"
