---
- name: Check if preflight_group_name already exists
  ansible.builtin.getent:
    database: group
    key: "{{ preflight_group_name }}"
  register: groups_result
  failed_when: "'msg' in groups_result and not preflight_allow_create_group"

- name: Ensure preflight_group_name exists
  become: true
  ansible.builtin.group:
    name: "{{ preflight_group_name }}"
    state: present
