---
# {{ ansible_managed }}

RabbitOptions:
  RabbitMqHostName: "localhost"
  RabbitMqHostPort: 5672
  RabbitMqVirtualHost: "smi_{{ config_name }}_file_extract"
  RabbitMqUserName: "guest"
  RabbitMqPassword: "guest"
  RabbitMqControlExchangeName: "ControlExchange"
  FatalLoggingExchange: "FatalLoggingExchange"

LoggingOptions:
  LogConfigFile: "{{ template_destpath | dirname }}/NLog.config.xml"
  LogsRoot: "/tmp/smi/logs/{{ config_name }}"
  TraceLogging: true

FileSystemOptions:
  FileSystemRoot: "/tmp/smi/PACS"
  ExtractRoot: "/tmp/smi/extract"
  DicomSearchPattern: "*.dcm"

RDMPOptions:
  CatalogueConnectionString:
  YamlDir:
  DataExportConnectionString:

MongoDatabases:
  ExtractionStoreOptions:
    HostName: "localhost"
    Port: 27017
    UserName:
    Password:
    DatabaseName: "extraction"

ExtractImagesOptions:
  MaxIdentifiersPerMessage: 1000
  ExtractionRequestProducerOptions:
    ExchangeName: "RequestExchange"
    MaxConfirmAttempts: 1
  ExtractionRequestInfoProducerOptions:
    ExchangeName: "RequestInfoExchange"
    MaxConfirmAttempts: 1
# ...
