---
- name: Ensure config dir exists
  become: true
  ansible.builtin.file:
    path: "{{ configs_configs_dir }}/{{ config_name }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Load extra vars file
  ansible.builtin.include_vars:
    dir: "{{ configs_configs_dir }}/{{ config_name }}"
    files_matching: _vars.yaml
    name: "{{ config_name }}_vars"

- name: Template config files
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ configs_configs_dir }}/{{ config_name }}/{{ item | basename }}"
    mode: u=rw,g=r,o=r
  with_ansible.builtin.fileglob: "{{ configs_template_dir }}/{{ config_name }}/*"
