---
- name: Stat config template dir
  ansible.builtin.stat:
    path: "{{ configs_template_dir }}/{{ env['name'] }}"
  register: stat_result

- name: Assert config template dir exists
  ansible.builtin.assert:
    that: stat_result.stat.exists and stat_result.stat.isdir
    msg: "Expected {{ configs_template_dir }}/{{ env['name'] }} to be a directory"

- name: Ensure config dir exists
  ansible.builtin.file:
    path: "{{ configs_configs_dir }}/{{ env['name'] }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Ensure config directory structure exists
  ansible.builtin.file:
    path: "{{ configs_configs_dir }}/{{ env['name'] }}//{{ item.path }}"
    state: directory
    mode: u=rwx,g=rx,o=rx
  with_community.general.filetree: "{{ configs_template_dir }}/{{ env['name'] }}"
  when: item.state == 'directory'

- name: Ensure files are populated from templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ configs_configs_dir }}/{{ env['name'] }}/{{ item.path }}"
    mode: u=rw,g=r,o=r
  with_community.general.filetree: "{{ configs_template_dir }}/{{ env['name'] }}"
  when: item.state == 'file'
