---
- name: Stat config template dir
  ansible.builtin.stat:
    path: "{{ configs_template_dir }}/{{ env_name }}"
  register: stat_result

- name: Assert config template dir exists
  ansible.builtin.assert:
    that: stat_result.stat.exists and stat_result.stat.isdir
    msg: "Expected {{ configs_template_dir }}/{{ env_name }} to be a directory"

- name: Load extra vars file
  ansible.builtin.include_vars:
    dir: "{{ configs_template_dir }}/{{ env_name }}"
    files_matching: _vars.yaml
    name: "{{ env_name }}_vars"

- name: Ensure config dir exists
  ansible.builtin.file:
    path: "{{ configs_configs_dir }}/{{ env_name }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Ensure config directory structure exists
  ansible.builtin.file:
    path: '{{ configs_configs_dir }}/{{ env_name }}//{{ item.path }}'
    state: directory
    mode: u=rwx,g=rx,o=rx
  with_community.general.filetree: "{{ configs_template_dir }}/{{ env_name }}"
  when: item.state == 'directory'

- name: Ensure files are populated from templates
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ configs_configs_dir }}/{{ env_name }}/{{ item.path }}'
    mode: u=rw,g=r,o=r
  with_community.general.filetree: '{{ configs_template_dir }}/{{ env_name }}'
  when: item.state == 'file' and not item.src.endswith("_vars.yaml")
