---
- name: Ensure configs dir exists
  become: true
  ansible.builtin.file:
    name: "{{ configs_configs_dir }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Check configs_smi_envs length
  ansible.builtin.assert:
    that: "{{ configs_smi_envs | length > 0 }}"
    msg: At least one smi_env must be defined for this role

- name: Deploy configs
  ansible.builtin.include_tasks: deploy_config_dir.yaml
  with_items: "{{ configs_smi_envs }}"
  loop_control:
    loop_var: env
