---
- name: Ensure configs dir exists
  become: true
  ansible.builtin.file:
    name: "{{ configs_configs_dir }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Deploy configs
  ansible.builtin.include_tasks: deploy_config_dir.yaml
  with_items: "{{ configs_smi_envs }}"
  loop_control:
    loop_var: env_name
