---
smi_service_software_install_dir: /opt/epcc/smi
smi_service_software_allow_create_install_dir: false

smi_service_software_smiservices_default_version: "5.4.0"
smi_service_software_smiservices:
  "5.4.0":
    release_packages_raw:
      - name: smi-services-v<VERSION>-linux-x64.tgz
        checksum: "md5:70464a712005361ef2b494f4682a36f9"
      - name: ctpanonymiser-v<VERSION>.zip
        checksum: "md5:14bb8575afd4b7da9c3ac73cd6179706"
      - name: SmiServices-<VERSION>-py3-none-any.whl
        checksum: "md5:c741416cc4ce9e6d9c8a9ff04da9b901"
    source_tar_checksum: "md5:426147dc2c622700a2f474ef2dfbc3ec"
    files_from_source:
      - "src/applications/SRAnonTool/CTP_SRAnonTool.sh"
smi_service_software_smiservices_file_blocklist:
  - default.yaml
  - DynamicRules.txt
  - Rules.template.yaml
  - Smi.NLog.config

smi_service_software_rdmp_default_version: "8.1.0"
smi_service_software_rdmp:
  "8.1.0":
    release_packages_raw:
      - name: rdmp-<VERSION>-cli-linux-x64.tar.xz
        checksum: "sha256:D3272CD6684B09AE295723138F124F570C28DC05D055CCC480A20B4F2992E638"
smi_service_software_rdmp_file_blocklist:
  - Databases.yaml
  - NLog.config

# Override this with an absolute path to a local directory of configs
smi_service_software_local_configs_template_dir: templates/configs

smi_service_software_logs_dir: /tmp/epcc/smi/logs
smi_service_software_allow_create_logs_dir: false

smi_service_software_pacs_dir: /tmp/epcc/smi/PACS
smi_service_software_allow_create_pacs_dir: false

smi_service_software_extract_dir: /tmp/epcc/smi/extract
smi_service_software_allow_create_extract_dir: false

smi_service_software_tessdata_version_or_sha: "4.1.0"
smi_service_software_tessdat_checksum: "md5:57e0df3d84fed9fbf8c7a8e589f8f012"

smi_service_software_patient_id_map_connection_string: "Server=localhost;Uid=root;Pwd=myStrongPassw0rd!;"
smi_service_software_patient_id_cache_connection_string: "localhost"
