---
- name: Ensure bin dir exists
  become: true
  ansible.builtin.file:
    name: "{{ smi_root }}/bin"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Template service scripts to bin
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ smi_root }}/bin/"
    mode: u=rwx,g=rx,o=rx
  with_ansible.builtin.fileglob: templates/bin/*
