---
- name: Ensure bin directory exists
  become: true
  ansible.builtin.file:
    name: "{{ smi_service_software_install_dir }}/bin"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Template service scripts to bin
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ smi_service_software_install_dir }}/bin/"
    mode: u=rwx,g=rx,o=rx
  with_ansible.builtin.fileglob: templates/*
