---
- name: Stat smi_base_dirs_software_dir
  ansible.builtin.stat:
    path: "{{ smi_base_dirs_software_dir }}"
  register: stat_result
  failed_when: not stat_result.stat.exists and not (smi_base_dirs_allow_create_software_dir or smi_base_dirs_allow_create_dirs)

- name: Ensure smi_base_dirs_software_dir exists
  become: true
  ansible.builtin.file:
    name: "{{ smi_base_dirs_software_dir }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Template README.md in smi_base_dirs_software_dir
  become: true
  ansible.builtin.template:
    src: root_readme.md
    dest: "{{ smi_base_dirs_software_dir }}/README.md"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Stat smi_base_dirs_logs_dir
  ansible.builtin.stat:
    path: "{{ smi_base_dirs_logs_dir }}"
  register: stat_result
  failed_when: not stat_result.stat.exists and not (smi_base_dirs_allow_create_logs_dir or smi_base_dirs_allow_create_dirs)

- name: Create smi_base_dirs_logs_dir
  become: true
  ansible.builtin.file:
    path: "{{ smi_base_dirs_logs_dir }}"
    owner: root
    group: "{{ smi_preflight_group_name }}"
    state: directory
    mode: u=rwx,g=rwxs,o=

- name: Stat smi_base_dirs_pacs_dir
  ansible.builtin.stat:
    path: "{{ smi_base_dirs_pacs_dir }}"
  register: stat_result
  failed_when: not stat_result.stat.exists and not (smi_base_dirs_allow_create_pacs_dir or smi_base_dirs_allow_create_dirs)

- name: Create smi_base_dirs_pacs_dir
  become: true
  ansible.builtin.file:
    path: "{{ smi_base_dirs_pacs_dir }}"
    owner: root
    group: "{{ smi_preflight_group_name }}"
    state: directory
    mode: u=rwx,g=rx,o=

- name: Stat smi_base_dirs_extractions_dir
  ansible.builtin.stat:
    path: "{{ smi_base_dirs_extractions_dir }}"
  register: stat_result
  failed_when: not stat_result.stat.exists and not (smi_base_dirs_allow_create_extractions_dir or smi_base_dirs_allow_create_dirs)

- name: Create smi_base_dirs_extractions_dir
  become: true
  ansible.builtin.file:
    path: "{{ smi_base_dirs_extractions_dir }}"
    owner: root
    group: "{{ smi_preflight_group_name }}"
    state: directory
    mode: u=rwx,g=rwxs,o=
