---
- name: Ensure smi_isidentifiable_base_dir exists
  ansible.builtin.file:
    path: "{{ smi_isidentifiable_base_dir }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Deploy IsIdentifiable versions
  environment: "{{ proxy_env | default({}) }}"
  ansible.builtin.script:
    cmd: |
      deploy_isidentifiable.py \
        {{ smi_isidentifiable_base_url }} \
        {{ smi_isidentifiable_base_dir }} \
        '{{ smi_isidentifiable_versions | to_json }}'
  register: deploy_result
  changed_when: deploy_result.rc != 0
