#!/usr/bin/env python3
import sys


def main() -> int:
    needle = "{{ ansible_managed }}"
    rc = 0

    for arg in sys.argv[1:]:
        with open(arg) as f:
            if needle in f.read():
                continue
            print(f"Did not find '{needle}' in {arg}")
            rc = 1

    return rc


if __name__ == "__main__":
    raise SystemExit(main())
