---
# TODO(rkm 2023-11-29) Move to own role?
- name: "service_software : Upload changed RabbitMQ configs"
  ansible.builtin.uri:
    url: "http://{{ smi_configs_rabbitmq_hostname }}:15672/api/definitions"
    method: "POST"
    src: "{{ item.dest }}"
    body_format: "json"
    remote_src: true
    force_basic_auth: true
    user: "guest"
    password: "guest"
    status_code: 204
  with_items: "{{ config_files | community.general.json_query('results[?changed]') }}"
  when: "item.dest is search('rabbitmq.*\\.json')"
  # No way to determine the applied changes
  changed_when: true
