---
smi_system_packages_install_list:
  - default-jre
  - git
  - htop
  - python3.10
  - python3.10-venv
  - tmux
  - unzip
  - vim

smi_system_journald_options:
  Storage: persistent
  SystemMaxUse: 4G

smi_system_motd_disabled_scripts:
  - 10-help-text
  - 90-updates-available
  - 98-reboot-required

smi_system_contact_email: "<None>"
