---
name: ansible-lint

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

env:
  python-version: "3.10"

defaults:
  run:
    shell: bash

jobs:
  ansible_lint:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}
      - name: install pre-commit
        run: python -m pip install --user --upgrade pip pre-commit
      - name: run ansible-lint
        run: pre-commit run --verbose ansible-lint
