---

- name: Set env_dir fact
  ansible.builtin.set_fact:
    env_dir: "{{ envs_envs_dir }}/{{ env_name }}"
    env_template_dir: "{{ envs_template_dir }}/{{ env_name }}"

- name: Ensure env dir exists
  ansible.builtin.file:
    path: "{{ env_dir }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Ensure env directory structure exists
  ansible.builtin.file:
    path: "{{ env_dir }}/{{ item.path }}"
    state: directory
    mode: u=rwx,g=rx,o=rx
  with_community.general.filetree: "{{ env_template_dir }}"
  when: item.state == 'directory'

- name: Load env vault.yaml
  ansible.builtin.include_vars:
    file: "{{ env_template_dir }}/vault.yaml"
    name: env_vault_vars

- name: Assert env_vault_vars defined
  ansible.builtin.assert:
    that: env_vault_vars is defined
    fail_msg: "Expected to load vars from file. A variable was possibly undefined (see https://github.com/ansible/ansible/issues/25787)"

- name: Load env vars.yaml
  ansible.builtin.include_vars:
    file: "{{ env_template_dir }}/vars.yaml"
    name: env_vars

- name: Assert env_vars defined
  ansible.builtin.assert:
    that: env_vars is defined
    fail_msg: "Expected to load vars from file. A variable was possibly undefined (see https://github.com/ansible/ansible/issues/25787)"

- name: Ensure files are populated from templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ env_dir }}/{{ item.path }}"
    mode: u=rw,g=r,o=r
  with_community.general.filetree: "{{ env_template_dir }}"
  when: item.state == 'file' and item.path not in ['vars.yaml', 'vault.yaml']

- name: Create venvs dir
  ansible.builtin.file:
    path: "{{ env_dir }}/venvs"
    state: directory
    mode: u=rwx,g=rx

- name: Create semehr venv
  environment: "{{ proxy_env | default({}) }}"
  ansible.builtin.pip:
    requirements: "{{ env_vars.semehr_venv_requirements }}"
    virtualenv: "{{ env_dir }}/venvs/semehr"
  when: env_vars.semehr_venv_requirements is defined

- name: Symlink scripts dir
  ansible.builtin.file:
    src: "{{ env_vars.scripts_dir }}"
    dest: "{{ env_dir }}/scripts"
    state: link
  when: env_vars.scripts_dir is defined

- name: Symlink IsIdentifiable rules dir
  ansible.builtin.file:
    src: "{{ env_vars.isidentifiable_rules_dir }}"
    dest: "{{ env_dir }}/IsIdentifiableRules"
    state: link
  when: env_vars.isidentifiable_rules_dir is defined

- name: Symlink RDMP repo dir
  ansible.builtin.file:
    src: "{{ env_vars.rdmp_repo_dir }}"
    dest: "{{ env_dir }}/rdmp"
    state: link
  when: env_vars.rdmp_repo_dir is defined
