---
- name: Ensure envs dir exists
  ansible.builtin.file:
    name: "{{ envs_envs_dir }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Register env names
  delegate_to: localhost
  ansible.builtin.find:
    paths: "{{ envs_template_dir }}"
    file_type: directory
    depth: 1
  register: env_names
  failed_when: env_names.matched == 0

- name: Deploy envs
  ansible.builtin.include_tasks: deploy_env_dir.yaml
  with_items: "{{ env_names.files | map(attribute='path') | map('basename') }}"
  loop_control:
    loop_var: env_name
